#ifndef __MENU
#define __MENU
#include <stdio.h>
typedef enum menu_t
    {
    OPENS_CREATE_ACCOUNT_WINDOW,
    OPENS_EDITING_WINDOW,
    OPENS_MAKE_TRANSACTION_WINDOW,
    OPENS_USER_ACCOUNT_DETAILS_WINDOW,
    OPENS_DELETING_USER_ACCCOUNT_WINDOW,
    OPENS_DISPLAY_USER_DETAILS_WINDOW,
    OPENS_ATM_FEATURES_WINDOW,
    OPENS_FUND_TRANSFER_WINDOW,
    OPENS_CURRENCY_EXCHANGE_WINDOW,
    CLOSES_WINDOW,
    } menu_t;


menu_t CASE(int choose);

#endif